version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  slack: circleci/slack@3.4.2
  heroku: circleci/heroku@1.2.2

commands:
  bundle_install:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  test_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: $CIRCLE_BRANCH のテストが完了しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-failed: $CIRCLE_BRANCH のテストが失敗しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

  deploy_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: $CIRCLE_BRANCH のデプロイが完了しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-failed: $CIRCLE_BRANCH のデプロイが失敗しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

workflows:
  test:
    jobs:
      - test

  heroku_deploy:
    jobs:
      - deploy_master:
          filters:
            branches:
                only: master


jobs:
  build:
    executor: ruby/default
    working_directory: ~/SmartOrder
    steps:
      - checkout
      - bundle_install

  test:
    executor: ruby/default
    working_directory: ~/SmartOrder
    steps:
      - checkout
      - bundle_install
      - run:
          name: rudocop
          command: bundle exec rudocop
      - test_notification


  deploy_master:
    executor: heroku/default # 標準の buildpack-deps イメージを使用します。このイメージは、Heroku の CLI をインストールする際に前提条件を提示します。
    steps:
      - checkout
      - heroku/install # 必要に応じて heroku インストール コマンドを実行します。
      - heroku/deploy-via-git:
        only-branch: master
      - deploy_notification
