version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  slack: circleci/slack@3.4.2
  heroku: circleci/heroku@1.2.2

jobs:
  slack-notification:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: exit 0
      - slack/status

  build:
    docker:
      - image: circleci/ruby:2.7.1-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: ruby -v
          command: ruby -v

  deploy:
    executor: heroku/default # 標準の buildpack-deps イメージを使用します。このイメージは、Heroku の CLI をインストールする際に前提条件を提示します。
    steps:
      - checkout
      - heroku/install # 必要に応じて heroku インストール コマンドを実行します。
      - run:
        name: Deploy Master to Heroku
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          fi

# workflows:
#   version: 2.1
#   my-workflow:
#     jobs:
#       - slack-notification
#   heroku_deploy:
#     jobs:
#       - deploy:
#         filters:
#           branches:
#             only:
#               - master
