version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  slack: circleci/slack@3.4.2
  heroku: circleci/heroku@1.2.2

workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - deploy_master:
        filters:
          branches:
            only: master
      - deploy-and-notify

jobs:
  build:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: ruby -v
          command: ruby -v

  deploy_master:
    executor: heroku/default # 標準の buildpack-deps イメージを使用します。このイメージは、Heroku の CLI をインストールする際に前提条件を提示します。
    steps:
      - checkout
      - heroku/install # 必要に応じて heroku インストール コマンドを実行します。
      - heroku/deploy-via-git:
        only-branch: master

  deploy-and-notify:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: ./deploy.sh
      - slack/status:
        success_message: ':circleci-pass: $CIRCLE_BRANCH のデプロイが完了しました\n:github_octocat: User：$CIRCLE_USERNAME'
        failure_message: ':circleci-fail: $CIRCLE_BRANCH のデプロイが失敗しました\n:github_octocat: User：$CIRCLE_USERNAME'
        webhook: '${SLACK_WEBHOOK}'
