version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  slack: circleci/slack@3.4.2
  heroku: circleci/heroku@1.2.2

# ---------------------------------

executors:
  default:
    working_directory: ~/SmartOrder
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: 'test'
      - image: circleci/mysql:8.0
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'

# ---------------------------------

commands:
  bundle_install:
    steps:
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler -v 2.1.4
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  test_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: $CIRCLE_BRANCH のテストが完了しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-failed: $CIRCLE_BRANCH のテストが失敗しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

  deploy_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: $CIRCLE_BRANCH のデプロイが完了しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-failed: $CIRCLE_BRANCH のデプロイが失敗しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

  run_rubocop:
    steps:
      - run:
          name: Rubocop
          command: bundle exec rubocop

  run_rspec:
    steps:
      - run:
          name: rspec
          command: bundle exec rspec

# ---------------------------------

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install

  test:
    executor:
      name: default
    steps:
      - run:
          name: pwd
          command: pwd
      - run_rubocop
      - run_rspec
      - test_notification

  deploy_master:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
        only-branch: master
      - deploy_notification

# ---------------------------------

workflows:
  test:
    jobs:
      - build:
          filters:
            branches:
                ignore: master
      - test:
          requires:
            - build
          filters:
            branches:
                ignore: master

  heroku_deploy:
    jobs:
      - build:
          filters:
            branches:
                only: master
      - test:
          filters:
            branches:
                only: master
      - deploy_master:
          requires:
            - build
            - test
          filters:
            branches:
                only: master
