version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  slack: circleci/slack@3.4.2
  heroku: circleci/heroku@1.2.2

executors:
  default:
    working_directory: ~/SmartOrder
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4

commands:
  bundle_install:
    steps:
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler -v 2.1.4
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  test_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: $CIRCLE_BRANCH のテストが完了しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-failed: $CIRCLE_BRANCH のテストが失敗しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

  deploy_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: $CIRCLE_BRANCH のデプロイが完了しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-failed: $CIRCLE_BRANCH のデプロイが失敗しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'


workflows:
  test:
    jobs:
      - test

  heroku_deploy:
    jobs:
      - deploy_master:
          filters:
            branches:
                only: master


jobs:
  build:
    working_directory: ~/SmartOrder
    executor: ruby/default
    steps:
      - checkout
      - bundle_install

  test:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install
      - run:
          name: rubocop
          command: bundle exec rudocop
      - test_notification


  deploy_master:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
        only-branch: master
      - deploy_notification
